/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myclassasist;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.table.DefaultTableModel;
import myclassasist.classpackage.databaseCon;
import myclassasist.classpackage.essentials;

/**
 *
 * @author Mr C
 */
public class attendance extends javax.swing.JFrame {

    /**
     * Creates new form attendance
     */
    public attendance() {
        initComponents();
       dataSet();
       loadCourse();
      txtsid.requestFocus();
    }
    
    public String sr;
    
    public void dataSet()
    {
     try{
            databaseCon db1=new databaseCon("root","");
            db1.connect();
            GregorianCalendar cal=new GregorianCalendar();
            int cdate=cal.get(Calendar.DAY_OF_WEEK);
            ResultSet rs = db1.getStatement().executeQuery("SELECT c_id FROM course_info WHERE cdayindex="+cdate+";");
  
            
            while(rs.next())
            {
                comcid.addItem(rs.getString(1));
               
            } 
            db1.disconnect();
            btnpay.setEnabled(false);
        }
        catch(Exception e){
            essentials.infomsgbox("Error",e.toString());
       
      }   
    }
    
    public void setCid()
    {
        
            String s1=(String) comcid.getSelectedItem();
            
            try{
            databaseCon db1=new databaseCon("root","");
            db1.connect();
            
            ResultSet rs = db1.getStatement().executeQuery("SELECT c.c_title,s.staff_name "
                    + " FROM course_info AS c INNER JOIN staff_info AS s ON "
                    + " s.staff_id=c.lec_id  AND c.c_id='"+s1+"' ;");
           
           while(rs.next())
            {
       
                lblcourse.setText(rs.getString(1));
                lbltutor.setText(rs.getString(2));
            } 
                
            comcid.requestFocus();
            db1.disconnect();
        }
        catch(Exception e){
            essentials.infomsgbox("Error",e.toString());
        }
    }
  
    
    
      public int payMonth()
    {
         int d = 0;
         String s1=txtsid.getText();
        String s2=(String) comcid.getSelectedItem();
         try{
            databaseCon db1=new databaseCon("root","");
            db1.connect();
            
            ResultSet rs = db1.getStatement().executeQuery("SELECT sum(nod) FROM payment_info WHERE std_id='"+s1+"' AND c_id='"+s2+"';");
           rs.next();
            d= rs.getInt(1);          
           
            db1.disconnect();
   
            
        }
        catch(Exception e){
            essentials.infomsgbox("Error",e.toString());
        }
       
         return d;
         
    }
  
     private void loadCourse()
    {
          String s2=((String) comcid.getSelectedItem()).toUpperCase();
        try{
            databaseCon db1=new databaseCon("root","");
            db1.connect();
            
            DefaultTableModel tb=(DefaultTableModel)tbattend.getModel();
           ResultSet rcount = db1.getStatement().executeQuery("SELECT count(std_id) FROM std_attendnce WHERE c_id='"+s2+"';");
            
           rcount.next();
            int n=rcount.getInt(1);
             tb.setRowCount(n); 
             
            ResultSet rs = db1.getStatement().executeQuery("SELECT std_id,a_daysattended,a_daysremain,a_status FROM std_attendnce"
                    + " WHERE c_id='"+s2+"' ;");
            int i=0;
             
            while(rs.next())
            {
                tb.setValueAt(rs.getString(1),i,0);               
               tb.setValueAt(rs.getInt(2), i, 1);
                tb.setValueAt(rs.getInt(3), i, 2);
                tb.setValueAt(rs.getString(4), i, 3);
                i++;
            } 
          tb.setRowCount(i);
            db1.disconnect();
        }
        catch(Exception e){
            essentials.infomsgbox("Error",e.toString());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title1 = new javax.swing.JLabel();
        back_up1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbattend = new javax.swing.JTable();
        jLabel18 = new javax.swing.JLabel();
        txtsid = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        lbltutor = new javax.swing.JLabel();
        lblcourse = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        lblname = new javax.swing.JLabel();
        lblnic = new javax.swing.JLabel();
        lblmobile = new javax.swing.JLabel();
        lblhome = new javax.swing.JLabel();
        lblstatus = new javax.swing.JLabel();
        lblstat = new javax.swing.JLabel();
        btnreg = new javax.swing.JButton();
        btnpay = new javax.swing.JButton();
        comcid = new javax.swing.JComboBox<>();
        btnreg1 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setTitle("EduAssist v1.0 Attendance");
        setPreferredSize(new java.awt.Dimension(850, 620));
        setResizable(false);
        getContentPane().setLayout(null);

        title1.setFont(new java.awt.Font("Calibri", 1, 48)); // NOI18N
        title1.setForeground(new java.awt.Color(51, 0, 51));
        title1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        title1.setText("Attendance");
        getContentPane().add(title1);
        title1.setBounds(410, 20, 420, 80);

        back_up1.setBackground(new java.awt.Color(255, 255, 255));
        back_up1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myclassasist/calm-35843-36659-hd-wallpapers.jpg"))); // NOI18N
        getContentPane().add(back_up1);
        back_up1.setBounds(-30, -20, 890, 130);

        tbattend.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        tbattend.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Student ID", "Days Attended", "Days Remaining", "Fee status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbattend.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbattendMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbattend);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(440, 320, 390, 170);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 51));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel18.setText("Attendance History :");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(440, 290, 210, 30);

        txtsid.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtsid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsidActionPerformed(evt);
            }
        });
        txtsid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtsidKeyPressed(evt);
            }
        });
        getContentPane().add(txtsid);
        txtsid.setBounds(140, 140, 270, 40);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 51));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel19.setText("Student ID :");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(20, 140, 120, 30);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Course Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 14), new java.awt.Color(51, 51, 51))); // NOI18N
        jPanel2.setOpaque(false);

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 0, 51));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel27.setText("Course :");

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 0, 51));
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel29.setText("Tutor :");

        lbltutor.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lbltutor.setForeground(new java.awt.Color(51, 51, 51));
        lbltutor.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        lblcourse.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblcourse.setForeground(new java.awt.Color(51, 51, 51));
        lblcourse.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lbltutor, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                        .addGap(12, 12, 12))
                    .addComponent(lblcourse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblcourse, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbltutor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(440, 190, 390, 100);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Student Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 14), new java.awt.Color(51, 51, 51))); // NOI18N
        jPanel1.setOpaque(false);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 51));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel20.setText("Name :");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 51));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel21.setText("NIC    :");

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 51));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel25.setText("Mobile No :");

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 0, 51));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel26.setText("Home No  :");

        lblname.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblname.setForeground(new java.awt.Color(51, 51, 51));
        lblname.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        lblnic.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblnic.setForeground(new java.awt.Color(51, 51, 51));
        lblnic.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        lblmobile.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblmobile.setForeground(new java.awt.Color(51, 51, 51));
        lblmobile.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        lblhome.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblhome.setForeground(new java.awt.Color(51, 51, 51));
        lblhome.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        lblstatus.setFont(new java.awt.Font("Dialog", 1, 40)); // NOI18N
        lblstatus.setForeground(new java.awt.Color(51, 255, 51));
        lblstatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblstat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblstat.setForeground(new java.awt.Color(0, 0, 51));
        lblstat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblstatus, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel26)
                        .addGap(18, 18, 18)
                        .addComponent(lblhome, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblstat, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblnic, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblmobile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(268, 268, 268))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblnic, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblmobile, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblhome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblstatus, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(lblstat, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 200, 390, 290);

        btnreg.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnreg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myclassasist/Project_res/update.png"))); // NOI18N
        btnreg.setText("SUBMIT");
        btnreg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregActionPerformed(evt);
            }
        });
        getContentPane().add(btnreg);
        btnreg.setBounds(650, 520, 180, 50);

        btnpay.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnpay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myclassasist/Project_res/payment.png"))); // NOI18N
        btnpay.setText("PAYMENT");
        btnpay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpayActionPerformed(evt);
            }
        });
        getContentPane().add(btnpay);
        btnpay.setBounds(490, 530, 150, 40);

        comcid.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        comcid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comcidActionPerformed(evt);
            }
        });
        getContentPane().add(comcid);
        comcid.setBounds(560, 140, 270, 40);

        btnreg1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnreg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myclassasist/Project_res/register.png"))); // NOI18N
        btnreg1.setText("REGISTER");
        btnreg1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreg1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnreg1);
        btnreg1.setBounds(310, 530, 170, 40);

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 51));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel23.setText("Course ID :");
        getContentPane().add(jLabel23);
        jLabel23.setBounds(440, 140, 120, 30);

        jLabel2.setBackground(new java.awt.Color(0, 102, 102));
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 500, 850, 120);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 110, 850, 510);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtsidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsidActionPerformed

    private void btnpayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpayActionPerformed
         String s2=(String) comcid.getSelectedItem();
        try{
            databaseCon db1=new databaseCon("root","");
            db1.connect();
            
             ResultSet rs3 = db1.getStatement().executeQuery("SELECT c_id,c_fee "
                    + "FROM course_info WHERE  c_id='"+s2+"' ;");
                    
                    rs3.next();
                    
                    String dr= rs3.getString(1);
                     String cid= rs3.getString(2);
                    
        payment p1=new payment ("cf",sr,cid,dr);
                p1.setVisible(true);
                
                   }
        catch(Exception e){
            essentials.infomsgbox("Error",e.toString());
        
        }
    }//GEN-LAST:event_btnpayActionPerformed

    private void btnregActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregActionPerformed
 
            
            String s2=(String) comcid.getSelectedItem();
            
            try{
            databaseCon db1=new databaseCon("root","");
            db1.connect();
            
             ResultSet rs3 = db1.getStatement().executeQuery("SELECT a_daysremain "
                    + "FROM std_attendnce WHERE  c_id='"+s2+"' ;");
                    
                    while(rs3.next())
                    { 
                    int dr= rs3.getInt(1);
                    
                       String upq=("UPDATE std_attendnce SET "
                        + "a_daysremain=?  WHERE  c_id='"+s2+"' AND a_daysremain='"+dr+"';");  
                     
                     db1.pStatement(upq);
                     db1.getPs().setInt(1, dr-1);
                     db1.getPs().executeUpdate();

                    }
                    
                  db1.disconnect();
                   essentials.infomsgbox("Done!","Details Updated Successfully.Session Ended!");
                  loadCourse(); 
        }
        catch(Exception e){
            essentials.infomsgbox("Error",e.toString());
        
        }
            btnreg.setEnabled(false);
    
    }//GEN-LAST:event_btnregActionPerformed

    private void txtsidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsidKeyPressed
         if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
           
            String s1=txtsid.getText();
            String s2=(String) comcid.getSelectedItem();
                         
            try{
            databaseCon db1=new databaseCon("root","");
            db1.connect();
              int i=0;
           ResultSet rcid = db1.getStatement().executeQuery("SELECT c_id FROM std_attendnce WHERE "
                   + "std_id='"+s1+"';");
           
             
               while(rcid.next())
               {
                   String rcs= rcid.getString(1).toUpperCase();
                   System.out.println(rcs);
                   if(rcs.equals(s2))
                              i=1;
         
               }
         
          if(i==1)
          {
             ResultSet rs = db1.getStatement().executeQuery("SELECT std_name,std_nic,std_mobileno,"
                    + "std_homeno FROM student_info WHERE "
                    + "std_id='"+s1+"';");
           
                rs.next();   
                        
                lblname.setText(rs.getString(1));
                lblnic.setText(rs.getString(2));
                lblmobile.setText(rs.getString(3));
                lblhome.setText(rs.getString(4));
                  
                    
                    ResultSet rs3 = db1.getStatement().executeQuery("SELECT a_daysattended "
                    + "FROM std_attendnce WHERE "
                    + "std_id='"+s1+"' AND c_id='"+s2+"' ;");
                    
                    rs3.next();
                    
                    int da= rs3.getInt(1);
                    
                  System.out.println(payMonth());
                  System.out.println(da);
                  
                    if(da<payMonth()+3)
                    {
                       
                        lblstatus.setText("Allowed");
                        lblstatus.setForeground(Color.green);
                        btnpay.setEnabled(false);
                        
                        
                        String upq=("UPDATE std_attendnce SET  a_daysattended=?,a_status=? "
                        + " WHERE std_id='"+s1+"' AND c_id='"+s2+"' ;");               
                    
                         db1.pStatement(upq);
                       
                         db1.getPs().setInt(1, da+1);
                         db1.getPs().setString(2, "Paid");
                          
                         db1.getPs().executeUpdate();
                         lblstat.setText(s1+" attendane updated successfully!");
                         loadCourse();
                         
                    }
                    else
                    { 
                         lblstatus.setText("Not Allowed");
                       lblstatus.setForeground(Color.red);
                       btnpay.setEnabled(true);
                       sr=txtsid.getText();
                       lblstat.setText("");
                                       }
               }
                else  {
                  essentials.infomsgbox("Error","No such Student enrolled to this course"); 
                  txtsid.setText("");
                  txtsid.requestFocus();
                            
                }
         
            db1.disconnect();
        }
        catch(Exception e){
            essentials.infomsgbox("Error",e.toString());
        }
        }
    }//GEN-LAST:event_txtsidKeyPressed

    private void comcidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comcidActionPerformed
          setCid();
    }//GEN-LAST:event_comcidActionPerformed

    private void btnreg1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreg1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnreg1ActionPerformed

    private void tbattendMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbattendMouseClicked
       
    }//GEN-LAST:event_tbattendMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(attendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(attendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(attendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(attendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new attendance().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back_up1;
    private javax.swing.JButton btnpay;
    private javax.swing.JButton btnreg;
    private javax.swing.JButton btnreg1;
    private javax.swing.JComboBox<String> comcid;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblcourse;
    private javax.swing.JLabel lblhome;
    private javax.swing.JLabel lblmobile;
    private javax.swing.JLabel lblname;
    private javax.swing.JLabel lblnic;
    private javax.swing.JLabel lblstat;
    private javax.swing.JLabel lblstatus;
    private javax.swing.JLabel lbltutor;
    private javax.swing.JTable tbattend;
    private javax.swing.JLabel title1;
    private javax.swing.JTextField txtsid;
    // End of variables declaration//GEN-END:variables
}
