/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myclassasist;

import java.sql.ResultSet;
import java.util.Calendar;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import myclassasist.classpackage.databaseCon;
import myclassasist.classpackage.essentials;

/**
 *
 * @author Mr C
 */
public class course_reg extends javax.swing.JFrame {

    /**
     * Creates new form course_reg
     */
    public course_reg() {
        initComponents();
        txtcid.requestFocus();
        refresh();
        
    }

    public void refresh()
    {
          DefaultTableModel tb=(DefaultTableModel)tbcourse.getModel();
        try{
            databaseCon db1=new databaseCon("root","");
            db1.connect();
            
             ResultSet rcount = db1.getStatement().executeQuery("SELECT count(c_id) FROM course_info  ;");
            
            rcount.next();
            int n=rcount.getInt(1);
             tb.setRowCount(n); 
            
            ResultSet rs = db1.getStatement().executeQuery("SELECT c_id,c_title,c_duration,lec_id,c_fee,c_lecfee,c_day,c_time,c_datereg FROM course_info;");
            int i=0;
            
            while(rs.next())
            {
               tb.setValueAt(rs.getString(1),i,0);
                tb.setValueAt(rs.getString(2), i, 1);
                tb.setValueAt(rs.getInt(3), i, 2);
               tb.setValueAt(rs.getString(4), i, 3);
               tb.setValueAt(rs.getDouble(5), i, 4);
                tb.setValueAt(rs.getDouble(6), i, 5);
               tb.setValueAt(rs.getString(7), i, 6);
               tb.setValueAt(rs.getString(8), i, 7);
               tb.setValueAt(rs.getDate(9), i, 8);
                i++;
            } 
            //tb.setRowCount(i);
            dataset();
            db1.disconnect();
        }
        catch(Exception e){
            essentials.infomsgbox("Error",e.toString());
        }
    }
    
    public void reset()
    {
        txtcid.setText("");
        txtctitle.setText("");
       txtduration.setText("");
       txttotal.setText("");
       txtlecfee.setText("");
       txtt1.setText(""); 
       txtt2.setText("");
        comlec.setSelectedIndex(0);
        comday.setSelectedIndex(0);
        txtcid.requestFocus();
         txtcid.setEditable(true);
            btndel.setEnabled(false);
            btnup.setEnabled(false);
        
    }
   
    
    public void dataset()
    {
         try{
            databaseCon db1=new databaseCon("root","");
            db1.connect();
            ResultSet rs = db1.getStatement().executeQuery("SELECT staff_id FROM staff_info WHERE staff_dtype = 'Tutor';");
            
           DefaultComboBoxModel commod= (DefaultComboBoxModel) comlec.getModel();
           commod.removeAllElements();
           
            while(rs.next())
            {
                commod.addElement(rs.getString(1));
               
            } 
            
            db1.disconnect();
        }
        catch(Exception e){
            essentials.infomsgbox("Error",e.toString());
        }
                
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title1 = new javax.swing.JLabel();
        back_up1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtcid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        comlec = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        txtctitle = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtduration = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txttotal = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtlecfee = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        comday = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        comtime1 = new javax.swing.JComboBox();
        txtt1 = new javax.swing.JTextField();
        txtt2 = new javax.swing.JTextField();
        comtime2 = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbcourse = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        btnsave = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        btnref = new javax.swing.JButton();
        btndel = new javax.swing.JButton();
        btnup = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setTitle("EduAssist v1.0 Course Management");
        setPreferredSize(new java.awt.Dimension(980, 760));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title1.setFont(new java.awt.Font("Calibri", 1, 48)); // NOI18N
        title1.setForeground(new java.awt.Color(51, 0, 51));
        title1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        title1.setText("Course Management");
        getContentPane().add(title1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, -1, 80));

        back_up1.setBackground(new java.awt.Color(255, 255, 255));
        back_up1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myclassasist/calm-35843-36659-hd-wallpapers.jpg"))); // NOI18N
        getContentPane().add(back_up1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 120));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Course Registration", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 14), new java.awt.Color(0, 0, 102))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(0, 0, 102));
        jPanel1.setOpaque(false);

        txtcid.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        txtcid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcidActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Course ID");

        comlec.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        comlec.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "lecid1", "lecid2" }));
        comlec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comlecActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 51));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Tutor ID");

        txtctitle.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        txtctitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtctitleActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 51));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Course Title");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 51));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Duration");

        txtduration.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        txtduration.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtduration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdurationActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Days");

        txttotal.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        txttotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txttotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttotalActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 51));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Monthly Fee(Rs.)");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 51));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Registration(Rs.)");

        txtlecfee.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        txtlecfee.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtlecfee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlecfeeActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 51));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Pref_Day");

        comday.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        comday.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", " " }));
        comday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comdayActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 51));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("Pref_Time");

        comtime1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        comtime1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AM", "PM" }));
        comtime1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comtime1ActionPerformed(evt);
            }
        });

        txtt1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        txtt1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtt1ActionPerformed(evt);
            }
        });

        txtt2.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        txtt2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtt2ActionPerformed(evt);
            }
        });

        comtime2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        comtime2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AM", "PM" }));
        comtime2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comtime2ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 51));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("-");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtlecfee, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtduration, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6))
                    .addComponent(txtcid, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtctitle, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comlec, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(txtt1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(comtime1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)
                                .addComponent(txtt2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comtime2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(comday, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtcid, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtduration, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtctitle, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(comlec, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comday, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtlecfee, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtt1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comtime1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtt2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comtime2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(24, 24, 24))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 930, 250));

        tbcourse.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        tbcourse.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Course ID", "Course Title", "Duration", "Lecturer", "Total Fee", "Registration Fee", "Preffered Day", "Preffered Time", "Date_registered"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbcourse.setOpaque(false);
        tbcourse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbcourseMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbcourse);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 930, 220));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 970, 0));

        btnsave.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnsave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myclassasist/Project_res/create.png"))); // NOI18N
        btnsave.setText("ADD NEW");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnsave, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 660, 150, 50));

        btnclear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnclear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myclassasist/Project_res/clear.png"))); // NOI18N
        btnclear.setText("CLEAR");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });
        getContentPane().add(btnclear, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 670, 120, 40));

        btnref.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnref.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myclassasist/Project_res/refresh.png"))); // NOI18N
        btnref.setText("REFRESH");
        btnref.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrefActionPerformed(evt);
            }
        });
        getContentPane().add(btnref, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 670, 130, 40));

        btndel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btndel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myclassasist/Project_res/delete.png"))); // NOI18N
        btndel.setText("DELETE");
        btndel.setEnabled(false);
        btndel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndelActionPerformed(evt);
            }
        });
        getContentPane().add(btndel, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 670, 120, 40));

        btnup.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myclassasist/Project_res/update.png"))); // NOI18N
        btnup.setText("UPDATE");
        btnup.setEnabled(false);
        btnup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupActionPerformed(evt);
            }
        });
        getContentPane().add(btnup, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 670, 130, 40));

        jLabel29.setBackground(new java.awt.Color(0, 102, 102));
        jLabel29.setOpaque(true);
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 640, 1030, 110));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 980, 630));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtcidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcidActionPerformed

    private void comlecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comlecActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comlecActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
            try{
             databaseCon dbadd = new databaseCon("root","");
             String s1 =txtcid.getText();
             String s2 =txtctitle.getText();
             int s3 = Integer.parseInt(txtduration.getText());
             double s4 =Double.parseDouble(txttotal.getText());
             double s5 =Double.parseDouble(txtlecfee.getText());
             double s6 =Double.parseDouble(txtt1.getText()); 
             double s7 =Double.parseDouble(txtt2.getText());
             String sc1=(String) comlec.getSelectedItem();
             String sc2=(String) comday.getSelectedItem();
             java.sql.Date dt=new java.sql.Date(Calendar.getInstance().getTimeInMillis());
             int nc = comday.getSelectedIndex()+1;
             int t1=(int)s6;
             int t2=(int)s7; 
             double td=(t2-t1) + (((s7-t2) - (s6-t1)));
             
             dbadd.connect();
             
             String saveq="INSERT INTO course_info VALUES(?,?,?,?,?,?,?,?,?,?,?);";
             dbadd.pStatement(saveq);
             
               dbadd.getPs().setString(1,s1);
               dbadd.getPs().setString(2,s2);
               dbadd.getPs().setInt(3, s3);
               dbadd.getPs().setString(4, sc1);
               dbadd.getPs().setDouble(5, s4);
               dbadd.getPs().setDouble(6, s5);
               dbadd.getPs().setString(7, sc2);
               dbadd.getPs().setString(8, s6+" - "+s7);
               dbadd.getPs().setDouble(9, td);
               dbadd.getPs().setDate(10,  dt);
               dbadd.getPs().setInt(11, nc);
               
               
               dbadd.getPs().execute();
               
              
   
             dbadd.disconnect();
             
              refresh();
              reset();
               essentials.infomsgbox("Success","Data added Successfully!");
             
         } 
         catch(Exception e){
              essentials.infomsgbox("Error",e.toString());
        }
        
       
                
    }                                      

    private void btndel1ActionPerformed(java.awt.event.ActionEvent evt) {                                        
     
      
    }//GEN-LAST:event_btnsaveActionPerformed

    private void btndelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndelActionPerformed
             try{
        databaseCon dbadd = new databaseCon("root","");
        String s1=txtcid.getText();
       
             dbadd.connect();
             
             
             
             String delq=("DELETE FROM course_info WHERE c_id='"+s1+"';");
             dbadd.pStatement(delq);
             dbadd.getPs().executeUpdate();
             
              dbadd.disconnect();
              
              
              refresh();
              reset();
              essentials.infomsgbox("Success","Data deleted Successfully!");
      }
      
      catch(Exception e){
              essentials.infomsgbox("Error",e.toString());
        }
    }//GEN-LAST:event_btndelActionPerformed

    private void btnrefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrefActionPerformed
       refresh();
    }//GEN-LAST:event_btnrefActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
      reset();
      refresh();
    }//GEN-LAST:event_btnclearActionPerformed

    private void txtctitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtctitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtctitleActionPerformed

    private void txtdurationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdurationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdurationActionPerformed

    private void txttotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttotalActionPerformed

    private void txtlecfeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlecfeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlecfeeActionPerformed

    private void comdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comdayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comdayActionPerformed

    private void comtime1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comtime1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comtime1ActionPerformed

    private void txtt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtt1ActionPerformed

    private void txtt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtt2ActionPerformed

    private void comtime2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comtime2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comtime2ActionPerformed

    private void tbcourseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbcourseMouseClicked
      int row=tbcourse.getSelectedRow();
            String rc=(tbcourse.getModel()).getValueAt(row,0).toString();
            if(!"".equals(rc)){   
        
        
        try{
           databaseCon db2 = new databaseCon("root","");
        
             db2.connect();
             
             
            String selque="SELECT c_id,c_title,c_duration,lec_id,c_fee,"
                    + "c_lecfee,c_day,c_time FROM course_info WHERE c_id='"+rc+"';";
            
            ResultSet rs = db2.getStatement().executeQuery(selque);
            
            
            while(rs.next())
            {
              txtcid.setText(rs.getString(1));  
              txtctitle.setText(rs.getString(2));
              txtduration.setText(rs.getString(3));
              comlec.setSelectedItem(rs.getString(4));
              txttotal.setText(rs.getString(5));
              txtlecfee.setText(rs.getString(6));
              comday.setSelectedItem(rs.getString(7));
              String t=rs.getString(8);
              txtt1.setText(t.substring(0,t.indexOf("-")-1)); 
              txtt2.setText(t.substring(t.indexOf("-")+1));
              
            }  
            
            txtcid.setEditable(false);
            btndel.setEnabled(true);
            btnup.setEnabled(true);
             db2.disconnect();
             
             
      }
      catch(Exception e){
              essentials.infomsgbox("Error",e.toString());
        }
             
}
              
    }//GEN-LAST:event_tbcourseMouseClicked

    private void btnupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupActionPerformed
        try{
             databaseCon dbup = new databaseCon("root","");
           
             String s1=txtcid.getText();
             String s2 =txtctitle.getText();
             int s3 =Integer.parseInt( txtduration.getText());
             double s4 =Double.parseDouble(txttotal.getText());
             double s5 =Double.parseDouble(txtlecfee.getText());
             double s6 =Double.parseDouble(txtt1.getText()); 
             double s7 =Double.parseDouble(txtt2.getText());
             String sc1=(String) comlec.getSelectedItem();
             String sc2=(String) comday.getSelectedItem();
             int nc = comday.getSelectedIndex();
             int t1=(int)s6;
             int t2=(int)s7; 
             double td=(t2-t1) + (((s7-t2) - (s6-t1)));
             
             dbup.connect();
             
             String upq=("UPDATE course_info SET  c_title=?, c_duration=?,lec_id=?,c_fee=?,c_lecfee=?,c_day=?,c_time=?,c_timeduration=?,cdayindex=? WHERE c_id='"+s1+"' ;");
             dbup.pStatement(upq);
             
             
               dbup.getPs().setString(1,s2);
               dbup.getPs().setInt(2, s3);
               dbup.getPs().setString(3, sc1);
               dbup.getPs().setDouble(4, s4);
               dbup.getPs().setDouble(5, s5);
               dbup.getPs().setString(6, sc2);
               dbup.getPs().setString(7, s6+" - "+s7);
               dbup.getPs().setDouble(8, td);
               dbup.getPs().setInt(9, nc);
               
               dbup.getPs().executeUpdate();
               
               
   
             dbup.disconnect();
             
            refresh();
            reset();
         
            essentials.infomsgbox("Success","Data Updated Successfully!");
         } 
         catch(Exception e){
              essentials.infomsgbox("Error",e.toString());
        }
    }//GEN-LAST:event_btnupActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(course_reg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(course_reg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(course_reg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(course_reg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new course_reg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back_up1;
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btndel;
    private javax.swing.JButton btnref;
    private javax.swing.JButton btnsave;
    private javax.swing.JButton btnup;
    private javax.swing.JComboBox comday;
    private javax.swing.JComboBox comlec;
    private javax.swing.JComboBox comtime1;
    private javax.swing.JComboBox comtime2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tbcourse;
    private javax.swing.JLabel title1;
    private javax.swing.JTextField txtcid;
    private javax.swing.JTextField txtctitle;
    private javax.swing.JTextField txtduration;
    private javax.swing.JTextField txtlecfee;
    private javax.swing.JTextField txtt1;
    private javax.swing.JTextField txtt2;
    private javax.swing.JTextField txttotal;
    // End of variables declaration//GEN-END:variables
}
