/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myclassasist;


import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.util.Calendar;
import java.util.HashMap;
import myclassasist.classpackage.databaseCon;
import myclassasist.classpackage.essentials;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Mr C
 */
public class payment extends javax.swing.JFrame {

    /**
     * Creates new form payment
     * @param status
     * @param sid
     * @param fee
     */
 
    
    public payment(String status,String sid,String fee,String cid) {
        initComponents();
        txtfee.requestFocus();
        if("pay".equals(status))
        {
            comfee.setSelectedIndex(1);
        }
        if("cf".equals(status))
        {
            comfee.setSelectedIndex(0);
        }
        
        setRecno();
        selectFee();
        txtsid.setText(sid);
        txtsid.setEnabled(true);
        txtfee.setText(fee);
        txtcid.setText(cid);
    }

    public void setRecno()
            {
                try{
                    
             databaseCon dbrec = new databaseCon("root","");
            
             dbrec.connect();
             
              String recq="SELECT pay_rec FROM payment_info ORDER BY pay_rec DESC; ";
               
              ResultSet rs = dbrec.getStatement().executeQuery(recq);
                rs.next();
                   
               int a = Integer.parseInt(rs.getString(1));
               a++;
               
               
                lblreciept.setText("00"+a);
            
            dbrec.disconnect();
    
         } 
         catch(Exception e){
              essentials.infomsgbox("Error",e.toString());
         }      
            }
    
    public payment()
    {
        initComponents();
        txtfee.requestFocus();
        setRecno();
        selectFee();
    }
 
    public String  recieptFormat(String date,String rcno,String ptype,String stname,String cid,String amount)
    {
        
        String f=String.format ("SIPYANA HIGH EDUCATIONAL INSTITUTE\n"
        + "----------------------MATARA---------------------\n"
        + "---------------Payment Reciept----------------\n"
        + "__________________________________\n"
        + "Date :- %s  Reciept No - %s\n"
        + "__________________________________\n"
        + "Payment Type :- %s\n\n"
        + "Student      :- %s\n\n"
                 + "Course      :- %s\n\n"
        + "__________________________________\n"       
        + "Amount       :- %s\n"
        + "__________________________________\n", date,rcno,ptype,stname,cid,amount);              
               
        return f;
    }
    
    void setEn(boolean a)
    {
     
           txtsid.requestFocus();
           txtnod.setEnabled(a);
            common.setEnabled(a);
            txtcid.setEnabled(a);
            
    }
    
    public void reset()
            {
            
            int s4= Integer.parseInt(lblreciept.getText())+1;
            
            lblreciept.setText(Integer.toString(s4));
            txtfee.setText("");
             txtsid.setText("Student Id");
             txtnod.setText("4");
             comfee.setSelectedIndex(0);
             common.setSelectedIndex(0);
             txtbill.setText("");
             //txtcid.setEnabled(false);
            
             txtnod.setEnabled(false);
             common.setEnabled(false);
             
          
            }
    
    void selectFee()
    {
        String newSelection = (String) comfee.getSelectedItem();
           
        if("Class Fee".equals(newSelection))
        {
          setEn(true);
          txtcid.requestFocus();
          txtnod.setText("4");
        }
        else
        {
            setEn(false);
        }
        
    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtfee = new javax.swing.JTextField();
        comfee = new javax.swing.JComboBox();
        lblreciept = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        common = new javax.swing.JComboBox();
        txtnod = new javax.swing.JTextField();
        txtsid = new javax.swing.JTextField();
        txtcid = new javax.swing.JTextField();
        title1 = new javax.swing.JLabel();
        back_up1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtbill = new javax.swing.JTextArea();
        btnprint = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();

        setTitle("EduAssist v1.0 Payments");
        setPreferredSize(new java.awt.Dimension(400, 690));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Payments", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 14))); // NOI18N
        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(370, 240));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Reciept No :");

        txtfee.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtfee.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtfee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfeeActionPerformed(evt);
            }
        });
        txtfee.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtfeeKeyPressed(evt);
            }
        });

        comfee.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        comfee.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Class Fee", "Registration Fee", "Exam Fee", "Other" }));
        comfee.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comfeeItemStateChanged(evt);
            }
        });
        comfee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comfeeActionPerformed(evt);
            }
        });

        lblreciept.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblreciept.setForeground(new java.awt.Color(51, 51, 51));
        lblreciept.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblreciept.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 51));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Amount (Rs)");

        common.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        common.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec" }));
        common.setEnabled(false);
        common.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                commonActionPerformed(evt);
            }
        });

        txtnod.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtnod.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtnod.setText("0");
        txtnod.setEnabled(false);
        txtnod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnodActionPerformed(evt);
            }
        });

        txtsid.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtsid.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtsid.setText("Student ID");
        txtsid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsidActionPerformed(evt);
            }
        });

        txtcid.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtcid.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtcid.setText("Course ID");
        txtcid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcidActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtsid)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2))
                        .addGap(0, 19, Short.MAX_VALUE))
                    .addComponent(txtcid, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(comfee, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblreciept, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                        .addComponent(txtfee, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(txtnod, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(common, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblreciept, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(comfee, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(txtcid))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtnod, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(common, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(txtsid, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfee, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 380, 250));

        title1.setFont(new java.awt.Font("Calibri", 1, 32)); // NOI18N
        title1.setForeground(new java.awt.Color(51, 0, 51));
        title1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        title1.setText("Create Payment");
        getContentPane().add(title1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, 80));

        back_up1.setBackground(new java.awt.Color(255, 255, 255));
        back_up1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myclassasist/calm-35843-36659-hd-wallpapers.jpg"))); // NOI18N
        getContentPane().add(back_up1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 90));

        txtbill.setEditable(false);
        txtbill.setColumns(20);
        txtbill.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtbill.setRows(100);
        txtbill.setText("SIPYANA EDUCATIONAL INSTITUTE- MATARA\n\n");
        txtbill.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtbill);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 380, 220));

        btnprint.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnprint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myclassasist/Project_res/print.png"))); // NOI18N
        btnprint.setText("PRINT RECIEPT");
        btnprint.setEnabled(false);
        btnprint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprintActionPerformed(evt);
            }
        });
        getContentPane().add(btnprint, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 590, 180, 50));

        btnupdate.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnupdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myclassasist/Project_res/update.png"))); // NOI18N
        btnupdate.setText("UPDATE");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 590, 170, 50));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, 85, 410, 490));

        jLabel29.setBackground(new java.awt.Color(0, 102, 102));
        jLabel29.setOpaque(true);
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 410, 120));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtfeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfeeActionPerformed

    private void comfeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comfeeActionPerformed
       selectFee();
    }//GEN-LAST:event_comfeeActionPerformed

    private void commonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_commonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_commonActionPerformed

    private void txtnodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnodActionPerformed

    private void txtsidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsidActionPerformed

    private void comfeeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comfeeItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_comfeeItemStateChanged

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
           try{
             databaseCon dbadd = new databaseCon("root","");
            int s1=Integer.parseInt(lblreciept.getText());
            String s2=(String)comfee.getSelectedItem();           
            double s3=Double.parseDouble(txtfee.getText());
            int s4=common.getSelectedIndex();
            String s6=txtsid.getText();
            String s8=txtcid.getText();
        

            int s7=Integer.parseInt(txtnod.getText());
            
            //java.sql.Date date=new java.sql.Date(td.getTime());
             java.sql.Date reg=new java.sql.Date(Calendar.getInstance().getTimeInMillis());
             dbadd.connect();
             
            
              String saveq="INSERT INTO payment_info VALUES(?,?,?,?,?,?,?,?);";
                 dbadd.pStatement(saveq);
             
              
               dbadd.getPs().setInt(1,s1);
               dbadd.getPs().setString(2,s2);
               dbadd.getPs().setDouble(3,s3);
               dbadd.getPs().setInt(4,s4);
               dbadd.getPs().setDate(5,reg);
               dbadd.getPs().setString(6,s6);
               dbadd.getPs().setInt(7,s7);
                dbadd.getPs().setString(8,s8);
               dbadd.getPs().execute();
            
            
            dbadd.disconnect();
            btnprint.setEnabled(true);
              
               essentials.infomsgbox("Success","Data added Successfully!");
             
         } 
         catch(Exception e){
              essentials.infomsgbox("Error",e.toString());
        }
   
    }//GEN-LAST:event_btnupdateActionPerformed

    private void txtfeeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfeeKeyPressed
         if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
           
            String s1=txtfee.getText();
            String s2=(String)comfee.getSelectedItem();           
            String s3=txtsid.getText();
             String s5=txtcid.getText();
            String s4=lblreciept.getText();
            String td = essentials.thisDate();
            txtbill.setText(recieptFormat(td,s4,s2,s3,s5,s1));
        }    
    }//GEN-LAST:event_txtfeeKeyPressed

    private void btnprintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprintActionPerformed
           HashMap para=new HashMap();
      para.put("pay_rec",lblreciept.getText());   
        
        try{
          Class.forName("com.mysql.jdbc.Driver");
          System.out.println("Connecting ");
          Connection dbcon =DriverManager.getConnection("jdbc:mysql://localhost:3306/eduassist","root","");
          
          String REPORT = "D:\\MyclassAssistant\\MyclassAsist\\src\\myclassasist\\jreports\\rec.jrxml";
             JasperReport JASP_REP=JasperCompileManager.compileReport(REPORT);
             JasperPrint J_PRINT = JasperFillManager.fillReport(JASP_REP,para,dbcon);
             JasperViewer.viewReport(J_PRINT,false);
             
            
            }
            catch(Exception e)
            {
              System.out.print(e);
                       }  
           reset();
    }//GEN-LAST:event_btnprintActionPerformed

    private void txtcidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcidActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new payment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back_up1;
    private javax.swing.JButton btnprint;
    private javax.swing.JButton btnupdate;
    private javax.swing.JComboBox comfee;
    private javax.swing.JComboBox common;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblreciept;
    private javax.swing.JLabel title1;
    private javax.swing.JTextArea txtbill;
    private javax.swing.JTextField txtcid;
    private javax.swing.JTextField txtfee;
    private javax.swing.JTextField txtnod;
    private javax.swing.JTextField txtsid;
    // End of variables declaration//GEN-END:variables
}
