/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myclassasist;

import java.sql.ResultSet;
import java.util.Calendar;
import javax.swing.table.DefaultTableModel;
import myclassasist.classpackage.databaseCon;
import myclassasist.classpackage.essentials;
import myclassasist.classpackage.staff;

/**
 *
 * @author Mr C
 */
public class staff_reg extends javax.swing.JFrame {

    /**
     * Creates new form staff_reg
     */
    public staff_reg() {
        initComponents();
        txtsid.requestFocus();
        refresh();
    }
    
     public void refresh()
    {
       
        try{
            
              
            databaseCon db1=new databaseCon("root","");
            db1.connect();
            
            DefaultTableModel tb=(DefaultTableModel)tbstaff.getModel();
             ResultSet rcount = db1.getStatement().executeQuery("SELECT count(staff_id) FROM staff_info  ;");
            
            rcount.next();
            int n=rcount.getInt(1);
            tb.setRowCount(n); 
              
             
            ResultSet rs = db1.getStatement().executeQuery("SELECT * FROM staff_info;");
            int i=0;
            
            while(rs.next())
            {
               tb.setValueAt(rs.getString(1),i,0);
                tb.setValueAt(rs.getString(2), i, 1);
                tb.setValueAt(rs.getString(4), i, 3);
                tb.setValueAt(rs.getString(5), i, 4);
                tb.setValueAt(rs.getDate(6), i, 5);
                tb.setValueAt(rs.getInt(7), i, 6);
                tb.setValueAt(rs.getString(8), i, 7);
                tb.setValueAt(rs.getInt(9), i, 8);
                tb.setValueAt(rs.getInt(10), i, 9);
               tb.setValueAt(rs.getString(11), i, 10);
               tb.setValueAt(rs.getDate(12), i, 11);
                i++;
            } 
          // tb.setRowCount(i);
            db1.disconnect();
        }
        catch(Exception e){
            essentials.infomsgbox("Error",e.toString());
        }
    }
    
    
    public void reset()
    {
       txtsid.setText("");
       txtname.setText("");
       txtaddress.setText("");
       txtmobile.setText("");
       txthome.setText("");
       txtnic.setText("");
       txtmail.setText("");
       comdob.setCurrent(essentials.getCal());
       comtype.setSelectedIndex(0);
       comgen.setSelectedIndex(0);
       txtsid.requestFocus();
       txtsid.setEditable(true);
       btndel.setEnabled(false);
       btnup.setEnabled(false);
       comdob.setEnabled(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        back_up = new javax.swing.JLabel();
        details_panel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtmobile = new javax.swing.JTextField();
        txthome = new javax.swing.JTextField();
        scrolladdress = new javax.swing.JScrollPane();
        txtaddress = new javax.swing.JTextArea();
        comgen = new javax.swing.JComboBox();
        txtname = new javax.swing.JTextField();
        txtnic = new javax.swing.JTextField();
        txtsid = new javax.swing.JTextField();
        txtmail = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbstaff = new javax.swing.JTable();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        comtype = new javax.swing.JComboBox();
        comdob = new datechooser.beans.DateChooserCombo();
        title1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        back_up1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnsave = new javax.swing.JButton();
        btndel = new javax.swing.JButton();
        btnup = new javax.swing.JButton();
        btnref = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();

        title.setFont(new java.awt.Font("Calibri", 1, 48)); // NOI18N
        title.setForeground(new java.awt.Color(51, 0, 51));
        title.setText("Student Management");

        back_up.setBackground(new java.awt.Color(255, 255, 255));

        setTitle("EduAssist v1.0 Staff Management");
        setPreferredSize(new java.awt.Dimension(980, 780));
        setResizable(false);
        getContentPane().setLayout(null);

        details_panel.setOpaque(false);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Staff ID");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 51));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Full Name");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 51));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Gender");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 51));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Address");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 51));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Home_No");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 51));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Mobile_No");

        txtmobile.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        txtmobile.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtmobile.setToolTipText("");
        txtmobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmobileActionPerformed(evt);
            }
        });

        txthome.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        txthome.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txthome.setToolTipText("");
        txthome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthomeActionPerformed(evt);
            }
        });

        txtaddress.setColumns(20);
        txtaddress.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        txtaddress.setRows(5);
        scrolladdress.setViewportView(txtaddress);

        comgen.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        comgen.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));
        comgen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comgenActionPerformed(evt);
            }
        });

        txtname.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameActionPerformed(evt);
            }
        });

        txtnic.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        txtnic.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtnic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnicActionPerformed(evt);
            }
        });

        txtsid.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        txtsid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsidActionPerformed(evt);
            }
        });

        txtmail.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        txtmail.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtmail.setToolTipText("");
        txtmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmailActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 51));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("NIC No");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 51));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("V");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 51));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("E-mail");

        tbstaff.setAutoCreateRowSorter(true);
        tbstaff.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        tbstaff.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Staff ID", "Full Name", "NIC", "Gender", "Address", "DOB", "Age", "Designation", "Mobile_No", "Home_No", "E-mail", "Date_registered"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbstaff.setOpaque(false);
        tbstaff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbstaffMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbstaff);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 51));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel20.setText("DOB");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 51));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel21.setText("De_Type");

        comtype.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        comtype.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Manager", "Tutor", "Demostrator", "Receptionist", "Marker", "Asistant", "Trainee" }));
        comtype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comtypeActionPerformed(evt);
            }
        });

        comdob.setCurrentView(new datechooser.view.appearance.AppearancesList("Light",
            new datechooser.view.appearance.ViewAppearance("custom",
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Dialog", java.awt.Font.PLAIN, 12),
                    new java.awt.Color(187, 187, 187),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Dialog", java.awt.Font.PLAIN, 12),
                    new java.awt.Color(187, 187, 187),
                    new java.awt.Color(0, 0, 255),
                    true,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Dialog", java.awt.Font.PLAIN, 12),
                    new java.awt.Color(0, 0, 255),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Dialog", java.awt.Font.PLAIN, 12),
                    new java.awt.Color(128, 128, 128),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Dialog", java.awt.Font.PLAIN, 12),
                    new java.awt.Color(187, 187, 187),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Dialog", java.awt.Font.PLAIN, 12),
                    new java.awt.Color(187, 187, 187),
                    new java.awt.Color(255, 0, 0),
                    false,
                    false,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                (datechooser.view.BackRenderer)null,
                false,
                true)));
    comdob.setFieldFont(new java.awt.Font("Dialog", java.awt.Font.BOLD, 15));
    comdob.setNavigateFont(new java.awt.Font("Serif", java.awt.Font.PLAIN, 11));
    comdob.setCurrentNavigateIndex(0);

    javax.swing.GroupLayout details_panelLayout = new javax.swing.GroupLayout(details_panel);
    details_panel.setLayout(details_panelLayout);
    details_panelLayout.setHorizontalGroup(
        details_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(details_panelLayout.createSequentialGroup()
            .addGap(32, 32, 32)
            .addGroup(details_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(details_panelLayout.createSequentialGroup()
                    .addGroup(details_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(details_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(details_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(details_panelLayout.createSequentialGroup()
                            .addComponent(txtmobile, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txthome, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(scrolladdress, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(details_panelLayout.createSequentialGroup()
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(txtsid, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGap(66, 66, 66)
            .addGroup(details_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(details_panelLayout.createSequentialGroup()
                    .addGap(4, 4, 4)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, details_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(details_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(comgen, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(txtnic, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(comdob, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(comtype, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(txtmail, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(43, Short.MAX_VALUE))
        .addGroup(details_panelLayout.createSequentialGroup()
            .addComponent(jScrollPane1)
            .addContainerGap())
    );
    details_panelLayout.setVerticalGroup(
        details_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(details_panelLayout.createSequentialGroup()
            .addGap(14, 14, 14)
            .addGroup(details_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(details_panelLayout.createSequentialGroup()
                    .addGroup(details_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtsid, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(13, 13, 13)
                    .addGroup(details_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(14, 14, 14)
                    .addGroup(details_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(scrolladdress, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(details_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(details_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtmobile, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(txthome, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(details_panelLayout.createSequentialGroup()
                    .addGroup(details_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(txtnic, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(comgen, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(23, 23, 23)
                    .addComponent(comdob, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(21, 21, 21)
                    .addComponent(comtype, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(txtmail, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(details_panelLayout.createSequentialGroup()
                    .addGap(206, 206, 206)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(details_panelLayout.createSequentialGroup()
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(35, 35, 35)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(21, 21, 21)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGap(37, 37, 37)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(15, Short.MAX_VALUE))
    );

    getContentPane().add(details_panel);
    details_panel.setBounds(10, 130, 960, 510);

    title1.setFont(new java.awt.Font("Calibri", 1, 48)); // NOI18N
    title1.setForeground(new java.awt.Color(51, 0, 51));
    title1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    title1.setText("Staff Management");
    getContentPane().add(title1);
    title1.setBounds(570, 30, 374, 80);
    getContentPane().add(jSeparator1);
    jSeparator1.setBounds(0, 120, 1000, 10);

    back_up1.setBackground(new java.awt.Color(255, 255, 255));
    back_up1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myclassasist/calm-35843-36659-hd-wallpapers.jpg"))); // NOI18N
    getContentPane().add(back_up1);
    back_up1.setBounds(0, 0, 990, 120);

    jLabel11.setBackground(new java.awt.Color(255, 255, 255));
    jLabel11.setOpaque(true);
    getContentPane().add(jLabel11);
    jLabel11.setBounds(-90, 110, 1070, 530);

    btnsave.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
    btnsave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myclassasist/Project_res/register.png"))); // NOI18N
    btnsave.setText("REGISTER");
    btnsave.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnsaveActionPerformed(evt);
        }
    });
    getContentPane().add(btnsave);
    btnsave.setBounds(810, 670, 150, 50);

    btndel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    btndel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myclassasist/Project_res/delete.png"))); // NOI18N
    btndel.setText("DELETE");
    btndel.setEnabled(false);
    btndel.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btndelActionPerformed(evt);
        }
    });
    getContentPane().add(btndel);
    btndel.setBounds(410, 680, 120, 38);

    btnup.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    btnup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myclassasist/Project_res/update.png"))); // NOI18N
    btnup.setText("UPDATE");
    btnup.setEnabled(false);
    btnup.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnupActionPerformed(evt);
        }
    });
    getContentPane().add(btnup);
    btnup.setBounds(280, 680, 120, 38);

    btnref.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    btnref.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myclassasist/Project_res/refresh.png"))); // NOI18N
    btnref.setText("REFRESH");
    btnref.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnrefActionPerformed(evt);
        }
    });
    getContentPane().add(btnref);
    btnref.setBounds(540, 680, 130, 38);

    btnclear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    btnclear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myclassasist/Project_res/clear.png"))); // NOI18N
    btnclear.setText("CLEAR");
    btnclear.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnclearActionPerformed(evt);
        }
    });
    getContentPane().add(btnclear);
    btnclear.setBounds(680, 680, 120, 38);

    jLabel29.setBackground(new java.awt.Color(0, 102, 102));
    jLabel29.setOpaque(true);
    getContentPane().add(jLabel29);
    jLabel29.setBounds(-40, 640, 1030, 110);

    pack();
    setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void comtypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comtypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comtypeActionPerformed

    private void tbstaffMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbstaffMouseClicked
        int row=tbstaff.getSelectedRow();
            String rc=(tbstaff.getModel()).getValueAt(row,0).toString();
            if(!"".equals(rc)){
        
        try{
           databaseCon db2 = new databaseCon("root","");
        
             db2.connect();
             
         
            String selque="SELECT * FROM staff_info WHERE staff_id='"+rc+"';";
            
            ResultSet rs = db2.getStatement().executeQuery(selque);
            
            
            while(rs.next())
            {
                txtsid.setText(rs.getString(1));
                txtname.setText(rs.getString(2));
                txtnic.setText(rs.getString(3));
                comgen.setSelectedItem(rs.getString(4));
                txtaddress.setText(rs.getString(5));
                comdob.setCurrent(essentials.getCal());
                comtype.setSelectedItem(rs.getString(8));
                txtmobile.setText(rs.getString(9));
                txthome.setText(rs.getString(10));
                txtmail.setText(rs.getString(11));
            
              
            }  
            
            comdob.setEnabled(false);
            txtsid.setEditable(false);
            btndel.setEnabled(true);
            btnup.setEnabled(true);
             db2.disconnect();
             
             
      }
      catch(Exception e){
              essentials.infomsgbox("Error",e.toString());
        }
 }
    }//GEN-LAST:event_tbstaffMouseClicked

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
           reset();
           refresh();
    }//GEN-LAST:event_btnclearActionPerformed

    private void btnrefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrefActionPerformed
        refresh();
    }//GEN-LAST:event_btnrefActionPerformed

    private void btnupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupActionPerformed
          try{
             databaseCon dbup = new databaseCon("root","");
           
             String s1=txtsid.getText();
             String s2 =txtname.getText();
             int s3 = Integer.parseInt(txtnic.getText());
             String s4=(String) comgen.getSelectedItem();
             String s5= txtaddress.getText();
             String s7=(String) comtype.getSelectedItem();
             int s8 = Integer.parseInt(txtmobile.getText());      
             int s9 = Integer.parseInt(txthome.getText()); 
             String s10= txtmail.getText();
             
             dbup.connect();
             
             String upq=("UPDATE staff_info SET  staff_name=?, staff_nic=?,staff_gender=?,staff_address=?,staff_dtype=?,staff_mobileno=?,staff_homeno=?,staff_email=? WHERE staff_id='"+s1+"' ;");
             dbup.pStatement(upq);
             
             
             dbup.getPs().setString(1,s2);
               dbup.getPs().setInt(2, s3);
               dbup.getPs().setString(3, s4);
               dbup.getPs().setString(4, s5);
               dbup.getPs().setString(5, s7);
               dbup.getPs().setInt(6, s8);
               dbup.getPs().setInt(7, s9);
               dbup.getPs().setString(8,  s10);
               
               dbup.getPs().executeUpdate();
               
               
   
             dbup.disconnect();
             
            refresh();
            reset();
         
            essentials.infomsgbox("Success","Data Updated Successfully!");
         } 
         catch(Exception e){
              essentials.infomsgbox("Error",e.toString());
        }
    }//GEN-LAST:event_btnupActionPerformed

    private void btndelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndelActionPerformed
  try{
        databaseCon dbadd = new databaseCon("root","");
        String s1=txtsid.getText();
       
             dbadd.connect();
             
             
             
             String delq=("DELETE FROM staff_info WHERE staff_id='"+s1+"';");
             dbadd.pStatement(delq);
             dbadd.getPs().executeUpdate();
             
              dbadd.disconnect();
              
              
              refresh();
              reset();
              essentials.infomsgbox("Success","Data deleted Successfully!");
      }
      
      catch(Exception e){
              essentials.infomsgbox("Error",e.toString());
        }
    }//GEN-LAST:event_btndelActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
 try{
             
     databaseCon dbadd = new databaseCon("root","");
    
             
             String s1 =txtsid.getText();
             String s2 =txtname.getText();
             int s3 = Integer.parseInt(txtnic.getText());
             String s4=(String) comgen.getSelectedItem();
             String s5= txtaddress.getText();
             Calendar d1=comdob.getSelectedDate();
             java.sql.Date dob=new java.sql.Date(d1.getInstance().getTimeInMillis());
             int s6 = essentials.getYearIndex()-d1.get(Calendar.YEAR);
             String s7=(String) comtype.getSelectedItem();
             int s8 = Integer.parseInt(txtmobile.getText());      
             int s9 = Integer.parseInt(txthome.getText()); 
             String s10= txtmail.getText();
             java.sql.Date reg=new java.sql.Date(Calendar.getInstance().getTimeInMillis());
             
             dbadd.connect();
             
             String saveq="INSERT INTO staff_info VALUES(?,?,?,?,?,?,?,?,?,?,?,?);";
             dbadd.pStatement(saveq);
             
               dbadd.getPs().setString(1,s1);
               dbadd.getPs().setString(2,s2);
               dbadd.getPs().setInt(3, s3);
               dbadd.getPs().setString(4, s4);
               dbadd.getPs().setString(5,s5);
               dbadd.getPs().setDate(6, dob);
               dbadd.getPs().setInt(7, s6);
               dbadd.getPs().setString(8, s7);
               dbadd.getPs().setInt(9, s8);
               dbadd.getPs().setInt(10, s9);
               dbadd.getPs().setString(11,  s10);
               dbadd.getPs().setDate(12, reg);
               
               
               dbadd.getPs().execute();
               
              
   
             dbadd.disconnect();
             
              refresh();
              reset();
               essentials.infomsgbox("Success","Data added Successfully!");
             
         } 
         catch(Exception e){
              essentials.infomsgbox("Error",e.toString());
        }
    }//GEN-LAST:event_btnsaveActionPerformed

    private void txtmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmailActionPerformed

    private void txtsidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsidActionPerformed

    private void txtnicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnicActionPerformed

    private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameActionPerformed

    private void comgenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comgenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comgenActionPerformed

    private void txthomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthomeActionPerformed

    private void txtmobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmobileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmobileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(staff_reg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(staff_reg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(staff_reg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(staff_reg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new staff_reg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back_up;
    private javax.swing.JLabel back_up1;
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btndel;
    private javax.swing.JButton btnref;
    private javax.swing.JButton btnsave;
    private javax.swing.JButton btnup;
    private datechooser.beans.DateChooserCombo comdob;
    private javax.swing.JComboBox comgen;
    private javax.swing.JComboBox comtype;
    private javax.swing.JPanel details_panel;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JScrollPane scrolladdress;
    private javax.swing.JTable tbstaff;
    private javax.swing.JLabel title;
    private javax.swing.JLabel title1;
    private javax.swing.JTextArea txtaddress;
    private javax.swing.JTextField txthome;
    private javax.swing.JTextField txtmail;
    private javax.swing.JTextField txtmobile;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtnic;
    private javax.swing.JTextField txtsid;
    // End of variables declaration//GEN-END:variables
}
