/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myclassasist;

import javax.swing.table.DefaultTableModel;
import myclassasist.classpackage.databaseCon;
import java.sql.*;
import myclassasist.classpackage.essentials;


/**
 *
 * @author Mr C
 */
public class users extends javax.swing.JFrame {
    
    public users() {
        initComponents();      
        txtuname.requestFocus();
        refresh();
        
    }
    
    public void refresh()
    {
          
        try{
            databaseCon db1=new databaseCon("root","");
            db1.connect();
            
            DefaultTableModel tb=(DefaultTableModel)tbdata1.getModel();
        
             ResultSet rcount = db1.getStatement().executeQuery("SELECT count(username) FROM user_info  ;");
            
            rcount.next();
            int n=rcount.getInt(1);
             tb.setRowCount(n); 
              
             
            ResultSet rs = db1.getStatement().executeQuery("SELECT * FROM user_info;");
            int i=0;
            
            while(rs.next())
            {
                tb.setValueAt(rs.getString(1),i,0);
                tb.setValueAt(rs.getString(2), i, 1);
                tb.setValueAt(rs.getString(3), i, 2);
                i++;
            } 
           // tb.setRowCount(i);
            db1.disconnect();
        }
        catch(Exception e){
            essentials.infomsgbox("Error",e.toString());
        }
    }
    
    public void reset()
    {
        txtuname.setText("");
        txtpword.setText("");
        comboutype.setSelectedItem("admin");
        txtuname.requestFocus();
         txtuname.setEditable(true);
            btndel1.setEnabled(false);
            btnup1.setEnabled(false);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        back_up1 = new javax.swing.JLabel();
        title1 = new javax.swing.JLabel();
        details_panel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtmobile = new javax.swing.JTextField();
        txthome = new javax.swing.JTextField();
        scrolladdress = new javax.swing.JScrollPane();
        txtaddress = new javax.swing.JTextArea();
        comgen = new javax.swing.JComboBox();
        txtname = new javax.swing.JTextField();
        txtnic = new javax.swing.JTextField();
        txtsid = new javax.swing.JTextField();
        txtmail = new javax.swing.JTextField();
        btnsave = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btndel = new javax.swing.JButton();
        btnup = new javax.swing.JButton();
        btnref = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbdata = new javax.swing.JTable();
        txtyear = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtmonth = new javax.swing.JTextField();
        txtdate = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        comdesignation = new javax.swing.JComboBox();
        title2 = new javax.swing.JLabel();
        back_up2 = new javax.swing.JLabel();
        details_panel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtuname = new javax.swing.JTextField();
        btnadd = new javax.swing.JButton();
        btndel1 = new javax.swing.JButton();
        btnup1 = new javax.swing.JButton();
        btnref1 = new javax.swing.JButton();
        btnclear1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbdata1 = new javax.swing.JTable();
        jLabel23 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        comboutype = new javax.swing.JComboBox();
        txtpword = new javax.swing.JPasswordField();
        jLabel14 = new javax.swing.JLabel();

        back_up1.setBackground(new java.awt.Color(255, 255, 255));

        title1.setFont(new java.awt.Font("Calibri", 1, 48)); // NOI18N
        title1.setForeground(new java.awt.Color(51, 0, 51));
        title1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        title1.setText("Staff Management");

        details_panel.setOpaque(false);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Staff ID");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 51));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Full Name");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 51));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Gender");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 51));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Address");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 51));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Home_No");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 51));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Mobile_No");

        txtmobile.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        txtmobile.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtmobile.setToolTipText("");
        txtmobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmobileActionPerformed(evt);
            }
        });

        txthome.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        txthome.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txthome.setToolTipText("");
        txthome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthomeActionPerformed(evt);
            }
        });

        txtaddress.setColumns(20);
        txtaddress.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        txtaddress.setRows(5);
        scrolladdress.setViewportView(txtaddress);

        comgen.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        comgen.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));
        comgen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comgenActionPerformed(evt);
            }
        });

        txtname.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameActionPerformed(evt);
            }
        });

        txtnic.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        txtnic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnicActionPerformed(evt);
            }
        });

        txtsid.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        txtsid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsidActionPerformed(evt);
            }
        });

        txtmail.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        txtmail.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtmail.setToolTipText("");
        txtmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmailActionPerformed(evt);
            }
        });

        btnsave.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnsave.setText("REGISTER");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 51));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("NIC No");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 51));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("V");

        btndel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btndel.setText("DELETE");
        btndel.setEnabled(false);
        btndel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndelActionPerformed(evt);
            }
        });

        btnup.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnup.setText("UPDATE");
        btnup.setEnabled(false);
        btnup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupActionPerformed(evt);
            }
        });

        btnref.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnref.setText("REFRESH");
        btnref.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrefActionPerformed(evt);
            }
        });

        btnclear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnclear.setText("CLEAR");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 51));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("E-mail");

        tbdata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Staff ID", "Name", "NIC", "Gender", "Address", "DOB", "Age", "Designation", "Home_No", "Mobile_No", "E-mail", "Date_registered"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, true, true, false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbdata.setOpaque(false);
        tbdata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbdataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbdata);

        txtyear.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        txtyear.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtyear.setToolTipText("");
        txtyear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtyearActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 51));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel20.setText("DOB");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 51));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel21.setText("De_Type");

        txtmonth.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        txtmonth.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtmonth.setToolTipText("");
        txtmonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmonthActionPerformed(evt);
            }
        });

        txtdate.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        txtdate.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtdate.setToolTipText("");
        txtdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdateActionPerformed(evt);
            }
        });

        comdesignation.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        comdesignation.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Manager", "Senior Lecturer", "Junior Lecturer", "Demostrator", "Receptionist", "Marker", "Asistant", "Trainee" }));
        comdesignation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comdesignationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout details_panelLayout = new javax.swing.GroupLayout(details_panel);
        details_panel.setLayout(details_panelLayout);
        details_panelLayout.setHorizontalGroup(
            details_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(details_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(details_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(details_panelLayout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(166, 166, 166))
                    .addGroup(details_panelLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtsid, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(details_panelLayout.createSequentialGroup()
                        .addGroup(details_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(details_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(details_panelLayout.createSequentialGroup()
                                .addComponent(txtmobile, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txthome, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(details_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(details_panelLayout.createSequentialGroup()
                                .addGroup(details_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(details_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(details_panelLayout.createSequentialGroup()
                                        .addComponent(txtnic, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(1, 1, 1)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(comgen, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(details_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(details_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btnclear, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnref, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnup, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btndel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnsave, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(166, 166, 166))
                            .addGroup(details_panelLayout.createSequentialGroup()
                                .addGroup(details_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(details_panelLayout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtmail, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(details_panelLayout.createSequentialGroup()
                                        .addComponent(jLabel21)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(comdesignation, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, details_panelLayout.createSequentialGroup()
                                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtyear, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtmonth, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtdate, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
            .addGroup(details_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(details_panelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(scrolladdress, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(589, Short.MAX_VALUE)))
        );
        details_panelLayout.setVerticalGroup(
            details_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(details_panelLayout.createSequentialGroup()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(details_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(details_panelLayout.createSequentialGroup()
                        .addGroup(details_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(details_panelLayout.createSequentialGroup()
                                .addGroup(details_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtsid, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(13, 13, 13)
                                .addGroup(details_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(153, 153, 153))
                            .addGroup(details_panelLayout.createSequentialGroup()
                                .addGroup(details_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(details_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(comgen, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(details_panelLayout.createSequentialGroup()
                                        .addGroup(details_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(details_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtnic, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(details_panelLayout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addGap(10, 10, 10)))
                                        .addGap(47, 47, 47)))
                                .addGap(35, 35, 35)
                                .addGroup(details_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtyear, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtmonth, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtdate, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(83, 83, 83)))
                        .addGroup(details_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txthome, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(details_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtmobile, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtmail, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(details_panelLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(btnsave, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btndel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnup, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(details_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnref, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comdesignation, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnclear, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
            .addGroup(details_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(details_panelLayout.createSequentialGroup()
                    .addGap(102, 102, 102)
                    .addGroup(details_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(scrolladdress, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(311, Short.MAX_VALUE)))
        );

        setTitle("EduAssist v1.0 User Management");
        setPreferredSize(new java.awt.Dimension(715, 500));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title2.setFont(new java.awt.Font("Calibri", 1, 42)); // NOI18N
        title2.setForeground(new java.awt.Color(51, 0, 51));
        title2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        title2.setText("Add/Remove Users");
        getContentPane().add(title2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, -1, 80));

        back_up2.setBackground(new java.awt.Color(255, 255, 255));
        back_up2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myclassasist/calm-35843-36659-hd-wallpapers.jpg"))); // NOI18N
        getContentPane().add(back_up2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 100));

        details_panel1.setBackground(new java.awt.Color(255, 255, 255));
        details_panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 51));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Username");
        details_panel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 97, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 51));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Password");
        details_panel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 91, 30));

        txtuname.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        txtuname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtunameActionPerformed(evt);
            }
        });
        details_panel1.add(txtuname, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 187, 41));

        btnadd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnadd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myclassasist/Project_res/register.png"))); // NOI18N
        btnadd.setText("ADD USER");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });
        details_panel1.add(btnadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(558, 310, 140, 49));

        btndel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btndel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myclassasist/Project_res/delete.png"))); // NOI18N
        btndel1.setText("DELETE");
        btndel1.setEnabled(false);
        btndel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndel1ActionPerformed(evt);
            }
        });
        details_panel1.add(btndel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 120, 38));

        btnup1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnup1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myclassasist/Project_res/update.png"))); // NOI18N
        btnup1.setText("UPDATE");
        btnup1.setEnabled(false);
        btnup1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnup1ActionPerformed(evt);
            }
        });
        details_panel1.add(btnup1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 120, 38));

        btnref1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnref1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myclassasist/Project_res/refresh.png"))); // NOI18N
        btnref1.setText("RESET");
        btnref1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnref1ActionPerformed(evt);
            }
        });
        details_panel1.add(btnref1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 320, 120, 38));

        btnclear1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnclear1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myclassasist/Project_res/clear.png"))); // NOI18N
        btnclear1.setText("CLEAR");
        btnclear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclear1ActionPerformed(evt);
            }
        });
        details_panel1.add(btnclear1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 320, 110, 38));

        tbdata1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        tbdata1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "username", "password", "user_type"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbdata1.setOpaque(false);
        tbdata1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbdata1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbdata1);

        details_panel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 648, 170));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 51));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("User_Type");
        details_panel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 20, -1, 30));
        details_panel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, -1));

        comboutype.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        comboutype.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "admin", "marker", "student", "staff" }));
        comboutype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboutypeActionPerformed(evt);
            }
        });
        details_panel1.add(comboutype, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 60, 176, 42));
        details_panel1.add(txtpword, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, 187, 41));

        jLabel14.setBackground(new java.awt.Color(0, 102, 102));
        jLabel14.setOpaque(true);
        details_panel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 710, 100));

        getContentPane().add(details_panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 100, 740, 370));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtmobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmobileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmobileActionPerformed

    private void txthomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthomeActionPerformed

    private void comgenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comgenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comgenActionPerformed

    private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameActionPerformed

    private void txtnicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnicActionPerformed

    private void txtsidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsidActionPerformed

    private void txtmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmailActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
     
    }//GEN-LAST:event_btnsaveActionPerformed

    private void btndelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndelActionPerformed
       
    }//GEN-LAST:event_btndelActionPerformed

    private void btnupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupActionPerformed
       
    }//GEN-LAST:event_btnupActionPerformed

    private void btnrefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrefActionPerformed
       
    }//GEN-LAST:event_btnrefActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
       
    }//GEN-LAST:event_btnclearActionPerformed

    private void tbdataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbdataMouseClicked
            
    }//GEN-LAST:event_tbdataMouseClicked

    private void txtyearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtyearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtyearActionPerformed

    private void txtmonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmonthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmonthActionPerformed

    private void txtdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdateActionPerformed

    private void comdesignationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comdesignationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comdesignationActionPerformed

    private void txtunameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtunameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtunameActionPerformed

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
         try{
             databaseCon dbadd = new databaseCon("root","");
             String s1=txtuname.getText();
              String s2=txtpword.getText();
              String s3=(String) comboutype.getSelectedItem();
             dbadd.connect();
             
             String saveq="INSERT INTO user_info(username,password,user_type)VALUES(?,?,?);";
             dbadd.pStatement(saveq);
             
             dbadd.getPs().setString(1,s1);
              dbadd.getPs().setString(2,s2);
               dbadd.getPs().setString(3, s3);
               dbadd.getPs().execute();
               
              
   
             dbadd.disconnect();
             
              refresh();
              reset();
               essentials.infomsgbox("Success","Data added Successfully!");
             
         } 
         catch(Exception e){
              essentials.infomsgbox("Error",e.toString());
        }
        
       
                
    }//GEN-LAST:event_btnaddActionPerformed

    private void btndel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndel1ActionPerformed
      try{
        databaseCon dbadd = new databaseCon("root","");
        String s1=txtuname.getText();
        String s2=txtpword.getText();
        String s3=(String) comboutype.getSelectedItem();
             dbadd.connect();
             
             
             
             String delq=("DELETE FROM user_info WHERE username='"+s1+"';");
             dbadd.pStatement(delq);
             dbadd.getPs().executeUpdate();
             
              dbadd.disconnect();
              
              
              refresh();
              reset();
              essentials.infomsgbox("Success","Data deleted Successfully!");
      }
      
      catch(Exception e){
              essentials.infomsgbox("Error",e.toString());
        }
      
     
      
     
    }//GEN-LAST:event_btndel1ActionPerformed

    private void btnup1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnup1ActionPerformed
         try{
             databaseCon dbup = new databaseCon("root","");
             String s1=txtuname.getText();
              String s2=txtpword.getText();
              String s3=(String) comboutype.getSelectedItem();
             dbup.connect();
             
             String upq=("UPDATE user_info SET  password=? , user_type=? WHERE username='"+s1+"' ;");
             dbup.pStatement(upq);
             
             
              dbup.getPs().setString(1,s2);
               dbup.getPs().setString(2, s3);
               dbup.getPs().executeUpdate();
               
               
   
             dbup.disconnect();
             
            refresh();
            reset();
         
            essentials.infomsgbox("Success","Data Updated Successfully!");
         } 
         catch(Exception e){
              essentials.infomsgbox("Error",e.toString());
        }
       
    }//GEN-LAST:event_btnup1ActionPerformed

    private void btnref1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnref1ActionPerformed
         refresh();   
    }//GEN-LAST:event_btnref1ActionPerformed

    private void btnclear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclear1ActionPerformed
        reset();
    }//GEN-LAST:event_btnclear1ActionPerformed

    private void tbdata1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbdata1MouseClicked
       int row=tbdata1.getSelectedRow();
            String rc=(tbdata1.getModel()).getValueAt(row,0).toString();
            if(!"".equals(rc)){
        
        
        try{
           databaseCon db2 = new databaseCon("root","");
        
             db2.connect();
            String selque="SELECT * FROM user_info WHERE username='"+rc+"';";
            
            ResultSet rs = db2.getStatement().executeQuery(selque);
            
            
            while(rs.next())
            {
              txtuname.setText(rs.getString(1));  
              txtpword.setText(rs.getString(2));
              comboutype.setSelectedItem(rs.getString(3));
            }  
            
            txtuname.setEditable(false);
            btndel1.setEnabled(true);
            btnup1.setEnabled(true);
             db2.disconnect();
             
             
      }
      catch(Exception e){
              essentials.infomsgbox("Error",e.toString());
      }
   }
      
    }//GEN-LAST:event_tbdata1MouseClicked

    private void comboutypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboutypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboutypeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(users.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(users.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(users.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(users.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new users().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back_up1;
    private javax.swing.JLabel back_up2;
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btnclear1;
    private javax.swing.JButton btndel;
    private javax.swing.JButton btndel1;
    private javax.swing.JButton btnref;
    private javax.swing.JButton btnref1;
    private javax.swing.JButton btnsave;
    private javax.swing.JButton btnup;
    private javax.swing.JButton btnup1;
    private javax.swing.JComboBox comboutype;
    private javax.swing.JComboBox comdesignation;
    private javax.swing.JComboBox comgen;
    private javax.swing.JPanel details_panel;
    private javax.swing.JPanel details_panel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JScrollPane scrolladdress;
    private javax.swing.JTable tbdata;
    private javax.swing.JTable tbdata1;
    private javax.swing.JLabel title1;
    private javax.swing.JLabel title2;
    private javax.swing.JTextArea txtaddress;
    private javax.swing.JTextField txtdate;
    private javax.swing.JTextField txthome;
    private javax.swing.JTextField txtmail;
    private javax.swing.JTextField txtmobile;
    private javax.swing.JTextField txtmonth;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtnic;
    private javax.swing.JPasswordField txtpword;
    private javax.swing.JTextField txtsid;
    private javax.swing.JTextField txtuname;
    private javax.swing.JTextField txtyear;
    // End of variables declaration//GEN-END:variables
}
